### ISSUE TITLE
Make chat smaller

### ISSUE THREAD

**Issue by Mastinoxx** [Thource/resizable-chat#10]
I am looking for a plugin that does the opposite of what this does. if possible can you add the option to make the chat window smaller? right now its impossible to make my inventory window and minimap big enough to my liking without also making the chat window too big. i have to play with chat closed 90% of the time because it is inconvenient to have open.

**Comment by korvl38** [comment]
Yeah I thought this was what it's supposed to be. The chat's already way too big

**Comment by Thource** [comment]
I’m working on this, should be done soon

**Comment by iBrenky** [comment]
Sorry for bothering, but any update on this? :) Would be so cool to finally have a plugin that can make the chat smaller!

**Comment by iBrenky** [comment]
> I’m working on this, should be done soon

Sorry for bothering, but any update on this? :) Would be so cool to finally have a plugin that can make the chat smaller!

**Comment by Thource** [comment]
Will be implemented with https://github.com/runelite/plugin-hub/pull/6248
