### ISSUE TITLE
Lower chatbox render priority or reset size while other interfaces are open

### ISSUE THREAD

**Issue by feelwood** [Thource/resizable-chat#2]
Since the chat overlaps with the bank, perhaps an option to collapse the chat box when you open the bank interface?
Unfortunately with no way to move the bank interface over currently, having to manually close and then reopen the chat to see the bottom half of my bank is kind of a deal breaker. Which is a shame because this plugin is really nice.

**Comment by feelwood** [comment]
Is this plugin still being worked on?

**Comment by Thource** [comment]
> Is this plugin still being worked on?

I’ve been very busy recently, but I’m starting to get some more time again so I’ll be working on this again
