### ISSUE TITLE
Make chatbox buttons grow with chatbox width

### ISSUE THREAD

**Issue by jliima** [Thource/resizable-chat#5]
Would love it if the background of the chat buttons would also extend when changing the width of the chat. Now it looks off if making the chat wider. Other way to achieve a more aesthetic look would to spread the buttons evenly to the wider chat box. If both of these options would be toggleable that would be ideal. Anyway nice plugin!

**Comment by Thource** [comment]
Will be implemented with https://github.com/runelite/plugin-hub/pull/6248
